# Generated by Django 5.0 on 2024-01-21 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('completion_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p3', max_length=10)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'New'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='new', max_length=20)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_mngt.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_mngt.workitem')),
            ],
        ),
    ]
