# Generated by Django 5.0 on 2024-01-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_mngt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='status',
        ),
    ]
