# Generated by Django 5.0 on 2024-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeedetail_status_alter_employeedetail_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='status',
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='designation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
