# Generated by Django 5.0 on 2024-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeedetail_status_alter_department_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenupermission',
            name='permission_level',
            field=models.CharField(choices=[('is_staff', 'Is Staff'), ('not_staff', 'Not Staff')], default='not_staff', max_length=10),
        ),
    ]
